---
- include: ../../tor/tasks/tor_state.yml
  tags: [toggle_tor,toggle_silent]
- include: ../../common/tasks/other_env.yml
  tags: [toggle_tor,toggle_silent]
- include: ../../wlan/tasks/dhcpd_state.yml
  tags: [network_config]

- name: install services
  apt: name={{ item }} state={{ apt_target_state }} force=yes update_cache=yes cache_valid_time={{ apt_cache_time }}
  with_items:
    - openresolv
    - dnsmasq

- name: enable services
  service: name={{ item }} enabled=yes
  with_items:
    - dnsmasq

- name: add dnsmasq user to loggers group
  user: name=dnsmasq groups="tmp-logger" append=yes

- name: configure dnsmasq
  template: src=dnsmasq.j2 dest=/etc/dnsmasq.conf owner=root group=root mode=644
  notify: restart dnsmasq
  register: res
  tags:
    - toggle_tor
    - toggle_silent

- name: create dnsmasq log dir
  file: path={{default_settings.log.general.path}}/{{default_settings.log.dnsmasq.subdir}} state=directory mode=0755 owner=dnsmasq
  tags:
    - toggle_tor
    - toggle_silent

- name: ensure dnsmasq logfile exists
  copy:
    content: ""
    dest: "{{default_settings.log.general.path}}/{{default_settings.log.dnsmasq.subdir}}/{{default_settings.log.dnsmasq.logfiles.logname}}"
    force: no
    group: root
    owner: dnsmasq
    mode: 0640
  tags:
    - toggle_tor
    - toggle_silent

- name: create tmpfiles.d conf file
  template: src=systemd-log-dir dest=/usr/lib/tmpfiles.d/dnsmasq.conf
  tags:
    - toggle_tor
    - toggle_silent

- name: remove dnsmasq log files from other environment
  file: path={{other_env.default_settings.log.general.path}}/{{other_env.default_settings.log.dnsmasq.subdir}}/{{item.value}} state=absent
  with_dict: "{{other_env.default_settings.log.dnsmasq.logfiles}}"
  when: res|changed
  tags:
    - toggle_tor
    - toggle_silent

- name: check if dnsmasq-resolv.conf is link
  stat: path=/etc/dnsmasq-resolv.conf
  register: dnsres
  tags:
    - network_config

- name: remove dnsmasq-resolv.conf if link and dhcp
  file: path=/etc/dnsmasq-resolv.conf state=absent
  when: not mode == "static" and dnsres.stat.islnk is defined and dnsres.stat.islnk
  tags:
    - network_config

- name: copy the openresolv config file
  template: src=resolvconf.conf dest=/etc/resolvconf.conf mode="0644"
  notify:
    - restart dnsmasq
    - ifupdown eth0
  tags:
    - network_config

- name: modify logrotate.d entry
  template: src=logrotate.j2 dest=/etc/logrotate.d/dnsmasq mode=0644
  tags:
    - toggle_tor
    - toggle_silent

- name: configure systemd-resolved
  service: name=systemd-resolved state={{'started' if mode == "static" else 'stopped'}} enabled={{mode == "static"}}
  tags:
    - network_config

- name: remove dnsmasq-resolv.conf if static ip
  file: path=/etc/dnsmasq-resolv.conf state=absent
  when: mode == "static" and dnsres.stat.islnk is defined and not dnsres.stat.islnk
  tags:
    - network_config

- name: link dnsmasq-resolv.conf to /run/systemd/resolve/resolv.conf
  file: src=/run/systemd/resolve/resolv.conf dest=/etc/dnsmasq-resolv.conf state=link
  when: mode == "static" and dnsres.stat.islnk is defined and not dnsres.stat.islnk
  tags:
    - network_config
