---
- name: touch pull crontab
  shell: touch /etc/cron.d/ansible-pull

- name: touch user-agent crontab
  shell: touch /etc/cron.d/parse-user-agents
  
- name: restart rsyslog
  service: name=rsyslog state=restarted