---
- include: ../../common/tasks/other_env.yml
- include: apate_state.yml
  tags: [toggle_apate]

- name: create working directory for apate daemon
  file: path=/opt/apate state=directory recurse=yes mode=0771 owner=root group=root

- name: copy the apate files
  copy: src=apate/ dest=/opt/apate owner=root group=root mode=0774
  notify: restart apate

- name: copy apate init script
  template: src=init/apate dest=/etc/init.d/apate owner=root group=root mode=0755
  notify: restart apate

- name: copy apate service file
  template: src=init/apate.service dest=/etc/systemd/system/apate.service owner=root group=root mode=0644
  notify: restart apate
  register: service_file

- name: systemctl daemon-reload
  shell: /bin/systemctl daemon-reload
  when: service_file.changed

- name: create apate config dir
  file: path=/etc/apate state=directory recurse=yes mode=0771 owner=root group=root

- name: copy apate config file
  template: src=config.json dest=/etc/apate/config.json owner=root group=root mode=0755
  notify: restart apate

- name: install virtualenv, tcpdump
  apt: name={{ item }} state="{{ apt_target_state }}" force=yes update_cache=yes cache_valid_time="{{ apt_cache_time }}"
  with_items:
    - python-virtualenv
    - tcpdump
    - redis-server

- name: install requirements to virtualenv
  pip: requirements=/opt/apate/requirements.txt virtualenv=/opt/apate/venv
  notify: restart apate

- name: remove log files from other environment
  file: path={{other_env.default_settings.log.general.path}}/{{other_env.default_settings.log.apate.subdir}} state=absent

- name: modify logrotate.d entry
  template: src=logrotate.j2 dest=/etc/logrotate.d/apate mode=0644

- name: configure apate service
  service: name=apate state='{{ "started" if apate_enabled|bool else "stopped" }}' enabled='{{ apate_enabled|bool }}' use=service
  tags:
    - toggle_apate

- name: change keyspace event notification of redis-sever
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: '^notify-keyspace-events'
    line: 'notify-keyspace-events "EKxh"'
  notify: restart redis

- name: enable redis server
  service: name=redis-server enabled=yes use=service
